import numpy as np

BATCH_SIZE = 32

EPSILON_MAX = 1
EPSILON_MIN = 0.1
EPSILON_PERIOD = 10000

def epsilon(iter):
    return EPSILON_MIN + (EPSILON_MAX - EPSILON_MIN) * np.cos(3.14*iter/EPSILON_PERIOD)**2
    #return EPSILON_FINAL + (EPSILON_START - EPSILON_FINAL) / np.exp(iter/EPSILON_DECAY)

GAMMA = 0.99
TARGET_UPDATE = 5000

BOARD_SIZE = 16

ALPHA = 0.6
BETA = 0.4
